name: cliente_web
description: Aplicação Flutter Web para clientes da loja
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  api_compartilhado:
    path: ../../api_compartilhado

  cupertino_icons: ^1.0.8

  dio: ^5.4.0
  provider: ^6.0.5
  intl: ^0.19.0
  image_picker: ^1.0.7
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  http: ^1.2.0       
  shared_preferences: ^2.2.3
  connectivity_plus: ^5.0.0

flutter:
  uses-material-design: true
  
