name: vendedor_app
description: Aplicação Flutter para vendedores da loja
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Networking
  dio: ^5.4.0
  http: ^1.1.0

  # Estado e arquitetura
  provider: ^6.0.5

  # Segurança
  flutter_secure_storage: ^9.0.0

  # Datas e formatação
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
