name: vendedor_app
description: Aplicação Flutter para vendedores da loja
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  desktop_drop: ^0.4.4  
  cross_file: ^0.3.3+8  

  # Networking
  dio: ^5.4.0
  image_picker: ^1.0.7
  http: ^1.2.0
  http_parser: ^4.0.2

  # Estado e arquitetura
  provider: ^6.0.5

  # Segurança
  flutter_secure_storage: ^9.0.0

  # Datas e formatação
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
